id: IA555BBDB
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T14:34:34.888073'
last_modified: '2022-06-19T14:34:34.888086'
parser: null
source_metadata:
  title: Hagiography of rJe btsun Grags pa rgyal mtshan (1147-1216); Lamdre Lobshe,
    vol. ka, title no. 5, from the chronological biographies of the Lamdre lineage
    masters
  author: ས་སྐྱ་པཎྜི་ཏ་ཀུན་དགའ་རྒྱལ་མཚན།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-08-16);
    converted from external file, unrevised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), Kunga Dorje (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/182
  bases:
    26f5:
      title: Hagiography of rJe btsun Grags pa rgyal mtshan (1147-1216); Lamdre Lobshe,
        vol. ka, title no. 5, from the chronological biographies of the Lamdre lineage
        masters
      order: 1
      base_file: 26f5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
